name: Dev pull request
run-name: Build and store dev image build
on:
  push:
    branches:    
      - dev
jobs:
  Build:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: pull
        continue-on-error: true
        run: docker pull ${{ secrets.DOCKER_IMAGE }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build --tag=$GITHUB_RUN_NUMBER:$GITHUB_REF_NAME --cache-from=${{ secrets.DOCKER_IMAGE }}:latest .
      
      - name: Retag build image
        run: docker tag $GITHUB_RUN_NUMBER:$GITHUB_REF_NAME ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Remove Temp Build Image
        run: docker rmi -f $GITHUB_RUN_NUMBER:$GITHUB_REF_NAME

      - name: Cleanup temp build fragments
        run: docker-compose -p $GITHUB_RUN_NUMBER -f docker-compose.ci.yml down --remove-orphans

