name: Production Deployment
run-name: Deploying ${{ github.repository }} to Production  🚀
on:
  push:
    branches:    
      - main
jobs:
  Login-To-Docker:
    runs-on: self-hosted
    environment: production
    steps:
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p ${{ secrets.DOCKER_PASSWORD }}

