name: Production Deployment
run-name: Deploying ${{ github.repository }} to Production  🚀
on:
  push:
    branches:    
      - main
jobs:
  Build:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: pull
        continue-on-error: true
        run: docker pull ${{ secrets.DOCKER_IMAGE }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        run: ls

      - name: Build and push docker image
        run: docker build --tag=$GITHUB_RUN_NUMBER:$GITHUB_REF_NAME --cache-from=${{ secrets.DOCKER_IMAGE }}:latest .

      #lint 

      - name: Retag docker image
        run: docker tag $GITHUB_RUN_NUMBER:$GITHUB_REF_NAME ${{ secrets.DOCKER_IMAGE }}:main

      - name: push new images to docker
        run: docker push ${{ secrets.DOCKER_IMAGE }}:main
  
      - name: Remove Build Image
        run: docker rmi -f $GITHUB_RUN_NUMBER:$GITHUB_REF_NAME
      #   with:
      #     context: .
      #     push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag' && !startsWith(github.ref, 'refs/tags/v0.')}}
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
