name: Production Deployment
run-name: Deploying ${{ github.repository }} to Production  🚀
on:
  push:
    branches:    
      - main
jobs:
  Build:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }}:temp --cache-from=${{ secrets.DOCKER_IMAGE }}:latest .

      - name: Make Envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
          envkey_DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
          directory: .
          file_name: prod.env
          fail_on_empty: true
        
      - name: Stop Current App
        run: docker compose -f docker-compose.deploy.yml down
  
      - name: Cleanup Build Image
        run: docker rmi -f ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Retag Build Image
        run: docker tag ${{ secrets.DOCKER_IMAGE }}:temp ${{ secrets.DOCKER_IMAGE }}:latest

      - name: New app start
        run: docker compose -f docker-compose.deploy.yml up -d

      - name: Push build to docker
        run: docker push ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Cleanup Build Image
        run: docker rmi -f ${{ secrets.DOCKER_IMAGE }}:temp

      

