# name: Digital Ocean Deployment
# on:
#   pull_request:
#     branches:
#     - master

# jobs:
#   login to docker hub:
#     runs-on: ubuntu
#     steps:
#     - name: login
#       run: docker login -u ${{ secrets.dockerHubToken }} -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
#       run: docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
